export const mockCards = [
  {
    id: 1,
    title: 'Капучино',
    description: 'Классический итальянский кофе с молоком',
    price: 150,
    image: '/images/cappuccino.jpg',
  },
  {
    id: 2,
    title: 'Чизкейк',
    description: 'Нежный чизкейк с клубничным соусом',
    price: 200,
    image: '/images/cheesecake.jpg',
  },
  {
    id: 3,
    title: 'Американо',
    description:
      'Кофе, приготовленный методом пролива горячей воды через молотый кофе',
    price: 120,
    image: '/images/americano.jpg',
  },
  {
    id: 4,
    title: 'Круассан',
    description: 'Свежий французский круассан с маслом',
    price: 110,
    image: '/images/croissant.jpg',
  },
  {
    id: 5,
    title: 'Латте',
    description: 'Кофейный напиток с большим количеством молока',
    price: 160,
    image: '/images/latte.jpg',
  },
  {
    id: 6,
    title: 'Эклер',
    description: 'Французское пирожное с заварным кремом',
    price: 130,
    image: '/images/eclair.jpg',
  },
  {
    id: 7,
    title: 'Мокко',
    description: 'Кофе с шоколадом и молоком',
    price: 170,
    image: '/images/mocha.jpg',
  },
  {
    id: 8,
    title: 'Тирамису',
    description: 'Итальянский десерт с сыром маскарпоне и кофе',
    price: 220,
    image: '/images/tiramisu.jpg',
  },
  {
    id: 9,
    title: 'Флэт уайт',
    description: 'Крепкий кофе с молочной пенкой',
    price: 155,
    image: '/images/flatwhite.jpg',
  },
  {
    id: 10,
    title: 'Панини',
    description: 'Итальянский горячий сэндвич с ветчиной и сыром',
    price: 180,
    image: '/images/panini.jpg',
  },
];
